[build]
  command ="npm run build && npm run start"  # Change this if your build script is different
  functions = "functions"    # If you have serverless functions

[dev]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/:appointments"
  status = 200
  force = true
