[build]
  command = "npm run build"  # Change this if your build script is different
  functions = "functions"    # If you have serverless functions

[dev]
  publish = "public"
  functions = "functions"
